### ISSUE TITLE
tokenfactory custom message encoders

### ISSUE THREAD

**Issue by discoverdefiteam** [public-awesome/stargaze#1014]
Hi! wanted to open up this discussion and see if others would agree that it would be useful to implement the custom message encoders for the `x/tokenfactory` module?

Osmosis implements this feature [here](https://github.com/osmosis-labs/osmosis/blob/main/wasmbinding/wasm.go#L13), and it seems like this may be useful for calling the tokenfactory in custom contracts

**Comment by jhernandezb** [comment]
We are currently avoiding adding new custom bindings and rather going with stargate queries and messages you can find an example here https://github.com/jhernandezb/tokenfactory-example/blob/main/src/contract.rs
