### ISSUE TITLE
Don't allow a post with an existing body hash

### ISSUE THREAD

**Issue by shanev** [public-awesome/stargaze#303]

**Comment by shanev** [comment]
Ah this one requires a bit of thought, because we don't have a key that indexes by the body hash, and iterating through all posts is going to cost too much gas. 

This is really mostly an issue for native posts since the postID is an incrementing ID, where for all others it uses the platform's own ID. So to detect duplicates for non-native posts, we can simply make sure the (vendorID | postID) is different, which we already do.

One way to solve this for native posts is to maintain a store for just body hash for native posts. Then we can detect conflicts in O(1), trading off some extra storage.

**Comment by JakeHartnell** [comment]
Do we even want this for native posts? Especially with the addition of comments soon, it may make more sense to just let native posts be posted without checking for duplicates.

I imagine multiple people may want to reply to a post with "ngmi" or "wagmi" for example... starting to lean towards wanting to just close this... thoughts?

**Comment by the-frey** [comment]
Is there a hierarchy between posts and comments? Cos if they're both just native posts with an implied variant type, pointing to the same external content, then Jake might be right in that the solution is different metadata.... or something else.

**Comment by shanev** [comment]
Yeah okay to close.
