### ISSUE TITLE
Raspberry pi 4 arm64 compile error

### ISSUE THREAD

**Issue by tolon** [public-awesome/stargaze#347]
**Describe the bug**
error in the cosmWasm package during compilation.

go: downloading github.com/rs/cors v1.7.0
# github.com/CosmWasm/wasmvm/api
/usr/bin/ld: skipping incompatible ../../../../pkg/mod/github.com/!cosm!wasm/wasmvm@v0.13.0/api/libwasmvm.so when searching for -lwasmvm
/usr/bin/ld: cannot find -lwasmvm
collect2: error: ld returned 1 exit status
make: *** [Makefile:103: install] Error 2

ld: mode aarch64linux
attempt to open /usr/local/lib/aarch64-linux-gnu/libwasmvm.so failed
attempt to open /usr/local/lib/aarch64-linux-gnu/libwasmvm.a failed
attempt to open /lib/aarch64-linux-gnu/libwasmvm.so failed
attempt to open /lib/aarch64-linux-gnu/libwasmvm.a failed
attempt to open /usr/lib/aarch64-linux-gnu/libwasmvm.so failed
attempt to open /usr/lib/aarch64-linux-gnu/libwasmvm.a failed
attempt to open /usr/local/lib/libwasmvm.so failed
attempt to open /usr/local/lib/libwasmvm.a failed
attempt to open /lib/libwasmvm.so failed
attempt to open /lib/libwasmvm.a failed
attempt to open /usr/lib/libwasmvm.so failed
attempt to open /usr/lib/libwasmvm.a failed
attempt to open /usr/aarch64-linux-gnu/lib/libwasmvm.so failed
attempt to open /usr/aarch64-linux-gnu/lib/libwasmvm.a failed
ld: cannot find -lwasmvm

Operating System

Ubuntu 20.04.2 Server  Raspberry Pi 4 version 

Hardware  
Raspberry Pi4 8 GB  

![putty_OlL6NH2y0O](https://user-images.githubusercontent.com/1315633/111836409-46c4a180-8907-11eb-922e-d07772bcf7a5.png)

**Comment by tolon** [comment]
I was thinking of manually copying * .so files to try it wouldn't work?

**Comment by shanev** [comment]
Haven't tried that yet. If if it compiles and runs, the next step is to upload a contract to see if it works. Let me know if you get to that point and I can help out.

**Comment by faddat** [comment]
@tolon you're likely to feel significant pain on this, let me link you to the pain:

https://github.com/CosmWasm/wasmvm/issues/53

I think you'll probably be able to get it to **compile** but I am not real sure about the contracts angle.  

I have decided to take this on, but from the looks of it it isn't going to be something that goes very fast, and I don't have a ton of time to work on it.

**Comment by tolon** [comment]
I followed what you wrote on the other github. I don't think the team is very enthusiastic. When I compile it by debugging, they should fix the errors that come up.  I tried manually inserting the lib files from their compiled version. I got the same error

**Comment by jhernandezb** [comment]
closing for now, depends on wasmer.
