### ISSUE TITLE
Query contracts from the LCD

### ISSUE THREAD

**Issue by davideitel** [public-awesome/stargaze#557]
It seems that there is no way to query contracts from the light client daemon (LCD).

I tried the /wasm/v1/contract/{address}/smart/{queryData} API that is present in the Swagger interface, but I encounter a Not implemented error.

```
curl -X GET "http://<node-host>/wasm/v1/contract/stars1gc5wcdn9ges00w0l2cfxd7r2puyflak5dmkg26rsh083afmnrjxqu7sutd/smart/%7B%22mintable_num_tokens%22%3A%20%7B%7D%7D" -H  "accept: application/json"

{
  "code": 12,
  "message": "Not Implemented",
  "details": []
}
```

However, the same query works from the CLI:
```
starsd query wasm contract-state smart stars1gc5wcdn9ges00w0l2cfxd7r2puyflak5dmkg26rsh083afmnrjxqu7sutd '{"mintable_num_tokens": {}}' --ascii

data:
  count: 0
```
Would it be possible to add this endpoint to the LCD?

**Comment by jhernandezb** [comment]
I'll look into it tomorrow

**Comment by jhernandezb** [comment]
seems to be working for me `queryData` must be base64 encoded
