### ISSUE TITLE
Custom message to distribute from community pool

### ISSUE THREAD

**Issue by shanev** [public-awesome/stargaze#602]
Add a custom wasm message that gives access to https://github.com/cosmos/cosmos-sdk/blob/6f070623741fe0d6851d79ada41e6e2b1c67e236/x/distribution/keeper/fee_pool.go#L10.

This allows contracts to use community pool funds for specific incentives (i.e: rewarding operators for detecting NFT transfers and updating Marketplace state).

**Comment by jhernandezb** [comment]
Maybe a dedicated pool instead?
