### ISSUE TITLE
Missing `--node` flag for `starsd query ibc client status` command

### ISSUE THREAD

**Issue by taitruong** [public-awesome/stargaze#906]
using latest `starsd` version 12.0.1 and by checking `starsd query ibc client status --help`, I realized there's no `--node` flag. I also check other CLIs like junod and terrad and they have this flag.

**Comment by spoo-bar** [comment]
This was an issue with ibc-go <v5 which was fixed in the later versions. 
https://github.com/cosmos/ibc-go/commit/2a469428f080d00c1c35b08d6191b184d9dc094e

The upcoming stargaze v13 release has this fix included.
