### ISSUE TITLE
Research tiered governance, committees, or sortition for moderation

### ISSUE THREAD

**Issue by shanev** [public-awesome/stargaze#91]
Full governance for content moderation is overkill. Maybe we should divide it up into committees, one for moderation, one for user verification, one for curation checks, one for voting on software upgrades / parameters.

Something like this https://github.com/Kava-Labs/kava/tree/master/x/committee/spec.

Even this: https://github.com/regen-network/regen-ledger/tree/master/x/group (I built a bit of this during a hackathon in Berlin)

**Comment by shanev** [comment]
A simpler approach is to use [sorition](https://en.wikipedia.org/wiki/Sortition). So a random group of validators are selected for each moderation request. This requires an engaged validator community that monitors the proposals allocated to them. Of course, can use a notification service out-of-band to notify validators when proposals allocated to them are available for adjudication.

**Comment by JakeHartnell** [comment]
Personally, I like the committee approach more. It's useful for many things (moderation, verification, etc.).

I feel validators should be more focused on proposals related to the protocol itself (software upgrades, parameter changes, etc.). I am wary of creating too much work for them in governance. Once this get's past a certain scale there will be a large amount of moderation requests.

Which is not to say I'm against the sortition approach as a short term solution, but I think long term we will need things like "moderation committees" that are separate from protocol governance.
