### ISSUE TITLE
Cannot sync an archive node from genesis

### ISSUE THREAD

**Issue by sleepert** [public-awesome/stargaze#938]
Hello I have attempted to sync an archive node and run into the same issue on block 1961577
```
12:29PM INF ABCI Replay Blocks appHeight=1961577 module=consensus stateHeight=1961577 storeHeight=1961578
63
12:29PM INF Replay last block using real app module=consensus
62
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 0F0FCA6D59D478E1DA095B4110E70EF72E11DD37648EA89119431B4EABDB1C74, got 5FB95E17A8638237E6C556750DBC232DCF4353ED6EA7DBB68C8EC74D3CD192F1
```
this occurs after the v3 hardfork. the version i am using when this error occurs is `v3.0.0`. i have tried multiple different deployments and each time it fails on the same block.

The sync from genesis I have run and upgraded from the following versions:
`v1.1.2` upgrading to `v2.0.1` for the v2 hardfork then upgrading to `v3.0.0` for the v3 hardfork.
I cannot sync from genesis with v12 as I get an instant go panic on startup, its the same with v11. I have trying to sync from genesis with v10 and it does not panic but after leaving it for a few days it never progresses past block 1.

How can an archive node be synced and how can I get past block `1961577`. No matter what I try I just cant get past this block.

**Comment by jhernandezb** [comment]
Hey there how are you building the binaries? from v2 to v3 it will require having specific go version of preference. Another way could be using the docker container we publish to docker hub.
